on:
  release:
    types:
      - published

name: release

jobs:
  pypi:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: release

    permissions:
      # Used to authenticate to PyPI via OIDC.
      id-token: write
    if: startsWith(github.ref, 'refs/tags')
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: build
      run: pipx run build
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
